//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAOMUONSACH
    {
        public int MaBaoCaoMuon { get; set; }
        public Nullable<int> MaLoaiSach { get; set; }
        public string SoLuotMuon { get; set; }
        public string TiLe { get; set; }
    
        public virtual LOAI_SACH LOAI_SACH { get; set; }
    }
}
