//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_MUON_SACH
    {
        public int MaPhieuMuon { get; set; }
        public Nullable<int> MaDG { get; set; }
        public Nullable<int> MaSach { get; set; }
        public string NgayMuon { get; set; }
    
        public virtual DOC_GIA DOC_GIA { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
