//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_THU_PHAT
    {
        public int MaPhieu { get; set; }
        public Nullable<int> MaDG { get; set; }
        public string SoTienThu { get; set; }
    
        public virtual DOC_GIA DOC_GIA { get; set; }
    }
}
